# -*- coding: utf-8 -*-
"""ML_Lab4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/157X8_k3QAdWto53Qk_EvJwZyLsHtByMu
"""

#Repeating Lab 3 questions using AI models
#A2
# AI Tool Used: ChatGPT
# Used to generate the implementation of the encoding functions.

import pandas as pd

# Label Encoding
def label_encode(data, column):
    values = data[column].unique()

    for i, value in enumerate(values):
        data[column] = data[column].replace(value, i)

    return data


# One-Hot Encoding
def one_hot_encode(data, column):
    return pd.get_dummies(data, columns=[column])


# Load dataset
df = pd.read_excel("marketing_campaign.xlsx")

# Example
label_data = label_encode(df.copy(), "Education")
onehot_data = one_hot_encode(df.copy(), "Education")

print("Label Encoded:")
print(label_data[["Education"]].head())

print("\nOne-Hot Encoded:")
print(onehot_data.head())

# Used to generate the generalized Minkowski distance function.
def minkowski_distance(A, B, p):
    distance = 0

    for x, y in zip(A, B):
        distance += abs(x - y) ** p

    return distance ** (1 / p)


# Example vectors
A = [1, 2, 3]
B = [4, 5, 6]

# Manhattan distance: p = 1
print("Manhattan Distance:", minkowski_distance(A, B, 1))

# Euclidean distance: p = 2
print("Euclidean Distance:", minkowski_distance(A, B, 2))

#A3
# Used to generate the code for categorical encoding and dimensionality reduction.

import pandas as pd
from sklearn.decomposition import PCA

# Load dataset
df = pd.read_excel("marketing_campaign.xlsx")

# Find categorical columns
categorical_columns = df.select_dtypes(include="object").columns

# Convert categorical features using One-Hot Encoding
encoded_data = pd.get_dummies(df, columns=categorical_columns)

# Convert data to numerical form
encoded_data = encoded_data.astype(float)

# Handle missing values by dropping rows with NaN (PCA does not accept NaN natively)
encoded_data = encoded_data.dropna()

# Display dimensionality before reduction
print("Original number of features:", df.shape[1])
print("Number of features after encoding:", encoded_data.shape[1])

# Reduce dimensions to 2 using PCA
pca = PCA(n_components=2)
reduced_data = pca.fit_transform(encoded_data)

print("Number of features after PCA:", reduced_data.shape[1])

print("\nReduced Data:")
print(reduced_data[:5])

#A4
# Used to generate the generalized Minkowski distance function.

def minkowski_distance(A, B, p):
    distance = 0

    for x, y in zip(A, B):
        distance += abs(x - y) ** p

    return distance ** (1 / p)


# Example vectors
A = [1, 2, 3]
B = [4, 5, 6]

# Manhattan distance: p = 1
print("Manhattan Distance:", minkowski_distance(A, B, 1))

# Euclidean distance: p = 2
print("Euclidean Distance:", minkowski_distance(A, B, 2))

#A5
# Used to generate the code for calculating Minkowski distances
# for different values of p and plotting the results.

import pandas as pd
import matplotlib.pyplot as plt

# Load dataset
df = pd.read_excel("marketing_campaign.xlsx")

# Select numerical columns
num_data = df.select_dtypes(include="number").dropna()

# Take any two feature vectors
A = num_data.iloc[0].values
B = num_data.iloc[1].values

# Calculate distances for p = 1 to 10
p_values = range(1, 11)
distances = []

for p in p_values:
    distances.append(minkowski_distance(A, B, p))

# Plot
plt.plot(p_values, distances, marker="o")
plt.xlabel("p")
plt.ylabel("Minkowski Distance")
plt.title("Minkowski Distance for Different Values of p")
plt.show()

print("p values:", list(p_values))
print("Distances:", distances)

#A6
# Used to generate the comparison between the user-defined
# Minkowski function and SciPy's built-in function.

import pandas as pd
from scipy.spatial.distance import minkowski

# Load dataset
df = pd.read_excel("marketing_campaign.xlsx")

# Select numerical features
num_data = df.select_dtypes(include="number").dropna()

# Take two vectors
A = num_data.iloc[0].values
B = num_data.iloc[1].values

# Compare for different p values
for p in range(1, 4):

    my_distance = minkowski_distance(A, B, p)
    scipy_distance = minkowski(A, B, p)

    print("p =", p)
    print("My function:", my_distance)
    print("Scipy function:", scipy_distance)
    print()

#A7
# Used to generate the user-defined functions for dot product
# and Euclidean vector length.

import pandas as pd
import numpy as np

# Dot Product
def dot_product(A, B):
    result = 0

    for x, y in zip(A, B):
        result += x * y

    return result


# Euclidean Norm
def euclidean_norm(A):
    total = 0

    for x in A:
        total += x ** 2

    return total ** 0.5


# Load dataset
df = pd.read_excel("marketing_campaign.xlsx")

# Select numerical data
num_data = df.select_dtypes(include="number").dropna()

# Take two vectors
A = num_data.iloc[0].values
B = num_data.iloc[1].values

# Dot product comparison
print("My Dot Product:", dot_product(A, B))
print("NumPy Dot Product:", np.dot(A, B))

print()

# Euclidean norm comparison
print("My Euclidean Norm:", euclidean_norm(A))
print("NumPy Euclidean Norm:", np.linalg.norm(A))

#A8
# Used to generate the user-defined functions for mean,
# variance and standard deviation.

import pandas as pd

# Mean
def calculate_mean(data):
    return sum(data) / len(data)


# Variance
def calculate_variance(data):
    m = calculate_mean(data)

    total = 0

    for x in data:
        total += (x - m) ** 2

    return total / len(data)


# Standard Deviation
def calculate_std(data):
    return calculate_variance(data) ** 0.5


# Load dataset
df = pd.read_excel("marketing_campaign.xlsx")

# Select numerical columns
num_data = df.select_dtypes(include="number").dropna()

# Calculate statistics for every feature
for column in num_data.columns:

    data = num_data[column].values

    print("Feature:", column)
    print("Mean:", calculate_mean(data))
    print("Variance:", calculate_variance(data))
    print("Standard Deviation:", calculate_std(data))
    print()

#A9
# Used to generate the comparison between the user-defined
# statistical functions and NumPy's built-in functions.

import pandas as pd
import numpy as np

# Load dataset
df = pd.read_excel("marketing_campaign.xlsx")

# Select numerical columns
num_data = df.select_dtypes(include="number").dropna()

for column in num_data.columns:

    data = num_data[column].values

    # Values from our functions
    my_mean = calculate_mean(data)
    my_std = calculate_std(data)

    # Values from NumPy
    numpy_mean = np.mean(data)
    numpy_std = np.std(data)

    print("Feature:", column)

    print("My Mean:", my_mean)
    print("NumPy Mean:", numpy_mean)

    print("My Standard Deviation:", my_std)
    print("NumPy Standard Deviation:", numpy_std)

    print()

#A10
# AI Tool Used: ChatGPT
# Used to generate the histogram and statistical calculations
# for a selected feature.

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Load dataset
df = pd.read_excel("marketing_campaign.xlsx")

# Select one numerical feature
feature = "Income"

data = df[feature].dropna()

# Plot histogram
plt.hist(data, bins=10)

plt.xlabel(feature)
plt.ylabel("Frequency")
plt.title("Distribution of " + feature)

plt.show()

# Calculate statistics
print("Feature:", feature)
print("Mean:", np.mean(data))
print("Variance:", np.var(data))

#A11
#Comparison between Lab Sheet 3 and using AI to solve K-Means Algorithm
# AI Tool Used: ChatGPT
# Used to generate the implementation of the basic K-means algorithm
# based on the algorithm provided in the lab sheet.

import pandas as pd
import numpy as np


# Distance function
def minkowski_distance(A, B, p=2):
    total = 0

    for x, y in zip(A, B):
        total += abs(x - y) ** p

    return total ** (1 / p)


# K-Means function
def kmeans(data, k):

    # Step 1: Select first K points as initial centroids
    centroids = data[:k].copy()

    while True:

        # Step 2: Assign points to nearest centroid
        clusters = []

        for point in data:

            distances = []

            for centroid in centroids:
                distance = minkowski_distance(point, centroid, 2)
                distances.append(distance)

            clusters.append(np.argmin(distances))

        clusters = np.array(clusters)

        # Step 3: Calculate new centroids
        new_centroids = []

        for i in range(k):

            points = data[clusters == i]

            if len(points) > 0:
                new_centroids.append(points.mean(axis=0))
            else:
                new_centroids.append(centroids[i])

        new_centroids = np.array(new_centroids)

        # Step 4: Check if centroids have stopped changing
        if np.allclose(centroids, new_centroids):
            break

        centroids = new_centroids

    return clusters, centroids


# Load dataset
df = pd.read_excel("marketing_campaign.xlsx")

# Select numerical features
num_data = df.select_dtypes(include="number").dropna()

# Convert to NumPy array
data = num_data.values

# Perform K-means with K = 3
clusters, centroids = kmeans(data, 3)

print("Cluster assignments:")
print(clusters)

print("\nFinal Centroids:")
print(centroids)