# -*- coding: utf-8 -*-
"""ML_Lab_Sheet_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F1a6WcHc2iLZwZ0OqAOxp-Jwd33etMTQ
"""

#A1
import pandas as pd
import numpy as np
file = "Lab Session Data (1).xlsx"
df = pd.read_excel(file, sheet_name="Purchase data")
X = df[['Candies (#)', 'Mangoes (Kg)', 'Milk Packets (#)']].values
y = df['Payment (Rs)'].values
print("Feature Matrix (X):")
print(X)
print("\nOutput Vector (y):")
print(y)
print("\nDimensionality of Vector Space =", X.shape[1])
print("Number of vectors =", X.shape[0])
rank = np.linalg.matrix_rank(X)
print("Rank of Feature Matrix =", rank)
pseudo_inv = np.linalg.pinv(X)
cost = pseudo_inv @ y
print("\nEstimated Cost of Products")
print("Cost of one Candy = Rs.", round(cost[0],2))
print("Cost of one Kg Mango = Rs.", round(cost[1],2))
print("Cost of one Milk Packet = Rs.", round(cost[2],2))

#A3
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
file = "Lab Session Data (1).xlsx"
df = pd.read_excel(file, sheet_name="IRCTC Stock Price")
price = df["Price"]
print("Mean Price =", np.mean(price))
print("Variance =", np.var(price))
def my_mean(data):
    total = 0
    for x in data:
        total += x
    return total/len(data)
def my_variance(data):
    m = my_mean(data)
    total = 0
    for x in data:
        total += (x-m)**2
    return total/len(data)
print("\nOwn Mean =", my_mean(price))
print("Own Variance =", my_variance(price))

import time

runs = 10

numpy_time = []
own_time = []

for i in range(runs):

    start = time.time()
    np.mean(price)
    np.var(price)
    numpy_time.append(time.time()-start)

    start = time.time()
    my_mean(price)
    my_variance(price)
    own_time.append(time.time()-start)

print("Average NumPy Time =", np.mean(numpy_time),"seconds")
print("Average Own Function Time =", np.mean(own_time),"seconds")

import time

runs = 10

numpy_time = []
own_time = []

for i in range(runs):

    start = time.time()
    np.mean(price)
    np.var(price)
    numpy_time.append(time.time()-start)

    start = time.time()
    my_mean(price)
    my_variance(price)
    own_time.append(time.time()-start)

print("Average NumPy Time =", np.mean(numpy_time),"seconds")
print("Average Own Function Time =", np.mean(own_time),"seconds")

wednesday = df[df["Day"]=="Wed"]

sample_mean = wednesday["Price"].mean()

print("Population Mean =", df["Price"].mean())
print("Wednesday Mean =", sample_mean)
april = df[df["Month"]=="Apr"]

print("Population Mean =", df["Price"].mean())
print("April Mean =", april["Price"].mean())

loss = df[df["Chg%"]<0]

prob_loss = len(loss)/len(df)

print("Probability of Loss =", prob_loss)


wednesday = df[df["Day"]=="Wed"]

profit_wed = wednesday[wednesday["Chg%"]>0]

prob_profit_wed = len(profit_wed)/len(wednesday)

print("Probability of Profit on Wednesday =", prob_profit_wed)

wednesday = df[df["Day"]=="Wed"]

profit = wednesday[wednesday["Chg%"]>0]

conditional = len(profit)/len(wednesday)

print("P(Profit | Wednesday) =", conditional)

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))

plt.scatter(df["Day"], df["Chg%"])

plt.xlabel("Day")

plt.ylabel("Chg %")

plt.title("Chg% vs Day")

plt.grid(True)

plt.show()

#A4
import pandas as pd
import numpy as np

file = "Lab Session Data (1).xlsx"

df = pd.read_excel(file, sheet_name="thyroid0387_UCI")

print(df.head())

print(df.dtypes)

from sklearn.preprocessing import LabelEncoder

encoded_df = df.copy()

label = LabelEncoder()

for col in encoded_df.columns:

    if encoded_df[col].dtype == object:

        encoded_df[col] = label.fit_transform(encoded_df[col].astype(str))

print(encoded_df.head())

numeric = df.select_dtypes(include=np.number)

print(numeric.describe())

#Missing values
print(df.isnull().sum())

numeric = df.select_dtypes(include=np.number)

for col in numeric.columns:

    Q1 = numeric[col].quantile(0.25)

    Q3 = numeric[col].quantile(0.75)

    IQR = Q3-Q1

    lower = Q1-1.5*IQR

    upper = Q3+1.5*IQR

    outliers = numeric[(numeric[col]<lower) | (numeric[col]>upper)]

    print(col,":",len(outliers),"outliers")

numeric = df.select_dtypes(include=np.number)

print("Mean\n")

print(numeric.mean())

print("\nStandard Deviation\n")

print(numeric.std())

print("\nVariance\n")

print(numeric.var())

#A5
import pandas as pd
import numpy as np

file = "Lab Session Data (1).xlsx"
df = pd.read_excel(file, sheet_name="thyroid0387_UCI")

from sklearn.preprocessing import LabelEncoder

encoded_df = df.copy()
le = LabelEncoder()

for col in encoded_df.columns:
    if encoded_df[col].dtype == object:
        encoded_df[col] = le.fit_transform(encoded_df[col].astype(str))

encoded_df = encoded_df.fillna(0)
binary_df = (encoded_df > 0).astype(int)

v1 = binary_df.iloc[0].values
v2 = binary_df.iloc[1].values

f11 = np.sum((v1 == 1) & (v2 == 1))
f10 = np.sum((v1 == 1) & (v2 == 0))
f01 = np.sum((v1 == 0) & (v2 == 1))
f00 = np.sum((v1 == 0) & (v2 == 0))

JC = f11 / (f11 + f10 + f01)
SMC = (f11 + f00) / (f11 + f10 + f01 + f00)

print("f11 =", f11)
print("f10 =", f10)
print("f01 =", f01)
print("f00 =", f00)
print("\nJaccard Coefficient =", JC)
print("Simple Matching Coefficient =", SMC)

#A6
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

file = "Lab Session Data (1).xlsx"

df = pd.read_excel(file, sheet_name="thyroid0387_UCI")
encoded_df = df.copy()
le = LabelEncoder()

for col in encoded_df.columns:
    if encoded_df[col].dtype == object:
        encoded_df[col] = le.fit_transform(encoded_df[col].astype(str))

encoded_df = encoded_df.fillna(0)
A = encoded_df.iloc[0].values.astype(float)
B = encoded_df.iloc[1].values.astype(float)

dot_product = np.dot(A, B)
normA = np.linalg.norm(A)
normB = np.linalg.norm(B)

cosine_similarity = dot_product / (normA * normB)
print("Cosine Similarity =", cosine_similarity)

#A7
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder

file = "Lab Session Data (1).xlsx"

df = pd.read_excel(file, sheet_name="thyroid0387_UCI")
encoded = df.copy()
le = LabelEncoder()

for col in encoded.columns:
    if encoded[col].dtype == object:
        encoded[col] = le.fit_transform(encoded[col].astype(str))

encoded = encoded.fillna(0)
binary = (encoded > 0).astype(int)

n = 20

JC_matrix = np.zeros((n,n))
SMC_matrix = np.zeros((n,n))
COS_matrix = np.zeros((n,n))

for i in range(n):
    for j in range(n):
        a = binary.iloc[i].values
        b = binary.iloc[j].values
        f11 = np.sum((a==1)&(b==1))
        f10 = np.sum((a==1)&(b==0))
        f01 = np.sum((a==0)&(b==1))
        f00 = np.sum((a==0)&(b==0))

        if (f11+f10+f01)==0:
            JC = 0
        else:
            JC = f11/(f11+f10+f01)

        SMC = (f11+f00)/(f11+f10+f01+f00)

        JC_matrix[i,j]=JC
        SMC_matrix[i,j]=SMC

        x = encoded.iloc[i].values.astype(float)
        y = encoded.iloc[j].values.astype(float)

        COS_matrix[i,j] = np.dot(x,y)/(np.linalg.norm(x)*np.linalg.norm(y))

# Jaccard Heatmap
plt.figure(figsize=(8,6))
sns.heatmap(JC_matrix, annot=True, cmap="Blues")
plt.title("Jaccard Similarity")
plt.show()

# SMC Heatmap
plt.figure(figsize=(8,6))
sns.heatmap(SMC_matrix, annot=True, cmap="Greens")
plt.title("Simple Matching Coefficient")
plt.show()

# Cosine Heatmap
plt.figure(figsize=(8,6))
sns.heatmap(COS_matrix, annot=True, cmap="Reds")
plt.title("Cosine Similarity")
plt.show()

#A8
import pandas as pd
import numpy as np

file = "Lab Session Data (1).xlsx"
df = pd.read_excel(file, sheet_name="thyroid0387_UCI")
imputed = df.copy()
for col in imputed.columns:
    if imputed[col].dtype == object:
        imputed[col].fillna(imputed[col].mode()[0], inplace=True)
    else:
        Q1 = imputed[col].quantile(0.25)
        Q3 = imputed[col].quantile(0.75)
        IQR = Q3-Q1
        lower = Q1-1.5*IQR
        upper = Q3+1.5*IQR
        outliers = imputed[(imputed[col]<lower) | (imputed[col]>upper)]
        if len(outliers)==0:
            imputed[col].fillna(imputed[col].mean(), inplace=True)
        else:
            imputed[col].fillna(imputed[col].median(), inplace=True)
print(imputed.isnull().sum())
print("\nMissing values handled successfully.")

import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler

file = "Lab Session Data (1).xlsx"
df = pd.read_excel(file, sheet_name="thyroid0387_UCI")
scaled_df = df.copy()
numeric_columns = scaled_df.select_dtypes(include=np.number).columns
scaler = MinMaxScaler()
scaled_df[numeric_columns] = scaler.fit_transform(scaled_df[numeric_columns])

print(scaled_df.head())
print("\nSummary Statistics after Normalization\n")
print(scaled_df[numeric_columns].describe())