# -*- coding: utf-8 -*-
"""MLLab6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z4F4wU6bziTLnkT0_-i0YSPf5UUu1br9
"""

import numpy as np
import pandas as pd
import time
import unittest
from collections import Counter
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.datasets import make_classification
import warnings
warnings.filterwarnings('ignore')

# =====================================================================
# MODULE 1: AI-OPTIMIZED k-NN IMPLEMENTATION (Lab 6 - A1)
# GenAI Tool Used: Gemini (Optimized for Vectorization & Speed)
# =====================================================================

class AI_Optimized_KNN:
    """
    Highly optimized kNN using NumPy broadcasting and np.argpartition for O(N) sorting.
    GenAI Prompt: "Generate a highly optimized, fully vectorized kNN classifier in Python using NumPy."
    """
    def __init__(self, n_neighbors=3, metric='euclidean', weighted=False):
        self.k = n_neighbors
        self.metric = metric
        self.weighted = weighted
        self.X_train = None
        self.y_train = None

    def fit(self, X, y):
        self.X_train = np.array(X)
        self.y_train = np.array(y)
        return self

    def _compute_distances(self, X_test):
        # GenAI Optimization: Vectorized Euclidean distance using (a-b)^2 = a^2 + b^2 - 2ab
        if self.metric == 'euclidean':
            test_sq = np.sum(X_test**2, axis=1, keepdims=True)
            train_sq = np.sum(self.X_train**2, axis=1)
            cross_term = np.dot(X_test, self.X_train.T)
            dists = np.sqrt(np.maximum(test_sq + train_sq - 2 * cross_term, 0))
            return dists
        else:
            # Fallback for manhattan
            return np.sum(np.abs(X_test[:, np.newaxis] - self.X_train), axis=2)

    def predict(self, X_test):
        X_test = np.array(X_test)
        dists = self._compute_distances(X_test)

        # GenAI Optimization: Use argpartition instead of full sort (O(N) instead of O(N log N))
        knn_indices = np.argpartition(dists, self.k, axis=1)[:, :self.k]
        predictions = []

        for i, neighbor_idx in enumerate(knn_indices):
            neighbor_dists = dists[i, neighbor_idx]
            neighbor_labels = self.y_train[neighbor_idx]

            if not self.weighted:
                # Fast majority voting
                most_common = Counter(neighbor_labels).most_common(1)[0][0]
                predictions.append(most_common)
            else:
                # Distance-weighted voting
                weights = 1.0 / (neighbor_dists + 1e-8)
                weighted_votes = {}
                for label, w in zip(neighbor_labels, weights):
                    weighted_votes[label] = weighted_votes.get(label, 0) + w
                best_label = max(weighted_votes, key=weighted_votes.get)
                predictions.append(best_label)

        return np.array(predictions)

# =====================================================================
# MODULE 2: HUMAN-CODED k-NN (From Lab 5 for comparison)
# =====================================================================
class Human_KNN:
    """Basic iterative implementation from Lab 5 to serve as the baseline."""
    def __init__(self, n_neighbors=3):
        self.k = n_neighbors
    def fit(self, X, y):
        self.X_train, self.y_train = np.array(X), np.array(y)
    def predict(self, X_test):
        preds = []
        for test_pt in np.array(X_test):
            dists = [np.sqrt(np.sum((test_pt - train_pt)**2)) for train_pt in self.X_train]
            # Slower full sorting
            k_indices = np.argsort(dists)[:self.k]
            k_labels = [self.y_train[i] for i in k_indices]
            preds.append(Counter(k_labels).most_common(1)[0][0])
        return np.array(preds)

# =====================================================================
# MODULE 3: UNIT TEST SUITE (Lab 6 - A2)
# GenAI Tool Used: Gemini (Generated automated assertions)
# =====================================================================

class TestKNNModules(unittest.TestCase):

    def setUp(self):
        self.X_train = np.array([[1, 1], [2, 2], [10, 10], [11, 11]])
        self.y_train = np.array([0, 0, 1, 1])
        self.X_test = np.array([[1.5, 1.5], [10.5, 10.5]])

    def test_distance_computation(self):
        """Test AI optimized distance calculations."""
        model = AI_Optimized_KNN(n_neighbors=2)
        model.fit(self.X_train, self.y_train)
        dists = model._compute_distances(self.X_test)
        self.assertEqual(dists.shape, (2, 4))
        self.assertTrue(dists[0, 0] < dists[0, 2]) # Point 1 closer to train pt 1 than 3

    def test_predictions(self):
        """Test accurate prediction of obvious classes."""
        model = AI_Optimized_KNN(n_neighbors=2)
        model.fit(self.X_train, self.y_train)
        preds = model.predict(self.X_test)
        self.assertEqual(list(preds), [0, 1])

    def test_weighted_predictions(self):
        """Test distance-weighted voting logic."""
        model = AI_Optimized_KNN(n_neighbors=3, weighted=True)
        model.fit(self.X_train, self.y_train)
        # Point closer to class 1, but k=3 includes two class 0 points
        edge_case = np.array([[8, 8]])
        pred = model.predict(edge_case)
        self.assertEqual(pred[0], 1)

# =====================================================================
# MODULE 4: PERFORMANCE COMPARISON SCRIPT (Lab 6 - A3)
# =====================================================================

def evaluate_model(model, X_train, y_train, X_test, y_test, runs=10):
    """Averages execution time over N runs and calculates metrics."""
    times = []

    for _ in range(runs):
        start_time = time.time()
        model.fit(X_train, y_train)
        preds = model.predict(X_test)
        times.append(time.time() - start_time)

    avg_time = np.mean(times)
    acc = accuracy_score(y_test, preds)
    prec = precision_score(y_test, preds, average='macro')
    rec = recall_score(y_test, preds, average='macro')
    f1 = f1_score(y_test, preds, average='macro')

    return acc, prec, rec, f1, avg_time

if __name__ == "__main__":

    # 1. Run Unit Tests
    print("=" * 65)
    print("RUNNING UNIT TEST SUITE")
    print("=" * 65)
    unittest.main(argv=['first-arg-is-ignored'], exit=False)

    # 2. Setup Benchmark Dataset (Use your project data here)
    X, y = make_classification(n_samples=1000, n_features=10, n_classes=2, random_state=42)
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

    # 3. Initialize Models
    k_val = 5
    models = {
        "Human-Coded kNN": Human_KNN(n_neighbors=k_val),
        "AI-Optimized kNN": AI_Optimized_KNN(n_neighbors=k_val),
        "Scikit-Learn kNN": KNeighborsClassifier(n_neighbors=k_val)
    }

    print("\n" + "=" * 85)
    print("PERFORMANCE COMPARISON (Averaged over 10 runs)")
    print("=" * 85)
    print(f"{'Model Type':<20} | {'Accuracy':<10} | {'Precision':<10} | {'Recall':<10} | {'F1-Score':<10} | {'Time (sec)':<10}")
    print("-" * 85)

    results = []
    for name, model in models.items():
        acc, prec, rec, f1, avg_time = evaluate_model(model, X_train, y_train, X_test, y_test, runs=10)
        print(f"{name:<20} | {acc:.4f}     | {prec:.4f}     | {rec:.4f}     | {f1:.4f}     | {avg_time:.5f}")
        results.append((name, acc, prec, rec, f1, avg_time))

    print("=" * 85)